version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "SonarQubeToken"
    SONARQUBE_ENDPOINT: "SonarQubeEndpoint"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - echo "sonar.host.url=http://54.188.163.81:9000/" >> sonar-scanner-cli-3.3.0.1492-linux/conf/sonar-scanner.properties
      - cat sonar-scanner-cli-3.3.0.1492-linux/conf/sonar-scanner.properties
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
     
  build:
    commands:
	- sonar-scanner
	

