version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "SonarQubeToken"
    SONARQUBE_ENDPOINT: "SonarQubeEndpoint"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - find . -name sonar-scanner-3.3.0.1492-linux
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
     
  build:
    commands:
      - sonar-scanner
