version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "SonarQubeToken"
    SONARQUBE_ENDPOINT: "SonarQubeEndpoint"
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - rm -rf $MAVEN_HOME/conf/settings.xml
      - cat Sonarqube/settings.xml
      - cp Sonarqube/settings.xml $MAVEN_HOME/conf/settings.xml
      - cat $MAVEN_HOME/conf/settings.xml 
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - mvn clean verify sonar:sonar -Dmaven.test.failure.ignore
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

