version: 0.2

env:
  variables:
    SONAR_LOGIN: "34af341fff3ee884f75f2e5acf37ec84bc19371a"
    SONAR_HOST: "http://54.188.163.81:9000/"
    #You should use parameter-store here instead

phases:
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST