version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo ${SONARQUBE_TOKEN}
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
      - echo "sonar.host.url=http://34.219.14.111:9000/" >> ./sonar-scanner-3.3.0.1492-linux/conf/sonar-scanner.properties
     
  build:
    commands:
      - sonar-scanner
